[IS-683] - Add Completion Timestamp to NodeRollouts and NodeReplacements
pusher/navarchos pull request #22
Opened 2019-09-10 14:17 UTC by theobarberbany

This PR adds a completion timestamp to `NodeRollouts` and `NodeReplacements`. 

This provides the data for the handler for completed `NodeRollouts` and `NodeReplacements` to delete them automatically after a given time period

2019-09-11 10:22 UTC, JoelSpeed reviewed
I'm assuming the integration of the new field into the Status of both types will become a follow up PR?

2019-09-11 15:58 UTC, JoelSpeed requested changes
Have we implemented the status for the NodeReplacements yet? If so we should do the same updates there

2019-09-12 13:10 UTC, JoelSpeed requested changes
Found a couple of tests that need fixing, the rest is just nitpicks on formatting

2019-09-13 10:24 UTC, mthssdrbrg reviewed
LGTM, just two minor nitpicks :)

2019-09-13 10:48 UTC, JoelSpeed approved these changes
LGTM

2019-09-13 10:48 UTC, merged