[IS-636] - Implement Handler for Completed NodeRollouts
pusher/navarchos pull request #23
Opened 2019-09-11 15:46 UTC by theobarberbany

Implements the handler for `Completed` `NodeRollout`s. 

(to be merged after #22 )

2019-09-16 11:52 UTC, JoelSpeed requested changes
One thing to change but once that's done all good

You seem to have brought the linter changes into this PR, was that deliberate? Might be best to get the linter PR #27 merged first and then rebase this one on top

2019-09-16 16:05 UTC, DanielMorsing submitted a review, later dismissed

2019-09-17 09:32 UTC, JoelSpeed submitted a review, later dismissed

2019-09-18 09:44 UTC, JoelSpeed approved these changes

2019-09-18 09:44 UTC, merged