[IS-772] - Add Documentation
pusher/navarchos pull request #43
Opened 2019-10-21 14:36 UTC by theobarberbany

This PR updates the README.md with some basic documentation, and should hopefully be enough to get most users up and running!

2019-10-22 12:45 UTC, wonderhoss requested changes

2019-10-22 14:17 UTC, JoelSpeed requested changes

2019-10-23 20:07 UTC, mthssdrbrg reviewed
Looks nice! I've added some minor comments, feel free to do with them what you will :)

2019-10-24 13:14 UTC, JoelSpeed requested changes
Added some nits and I think there are a couple of errors still, ping me if any of them don't make sense

2019-10-24 15:53 UTC, JoelSpeed approved these changes

2019-10-25 09:13 UTC, wonderhoss approved these changes
LGTM

2019-10-25 09:46 UTC, merged